version: '3'
services:
  hue-bot:
    container_name: hue-bot
    build: ./
    volumes:
    - ./:/usr/src/app
    depends_on:
    - redis
    ports:
    - 5000:8080
    - 56745:56745
    environment:
    - NODE_ENV=production
    - PORT=8080
    links:
    - redis

  redis:
    image: redis
