version: '3'
services:
  hue-bot:
    build: ./
    volumes:
    - ./:/usr/src/app
    depends_on:
    - redis
    ports:
    - 5000:8080
    environment:
    - NODE_ENV=development
    - PORT=8080
    links:
    - redis

  redis:
    image: redis
