version: '3'
services:
  app:
    build: ./
    volumes:
    - ./:/usr/src/app
    ports:
    - 5000:8080
    environment:
    - NODE_ENV=development
    - PORT=8080
    - REDIS_URL=redis://cache
    links:
    - redis

  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
    ports:
      - "6379:6379"
